### ISSUE TITLE
Plotchart issues collection

### ISSUE THREAD

**Issue by EleonoraPetzold** [bexis/Module_ResearchAreaManagement#45]
- [ ]  EPs: logging trails werden nicht mehr angezeigt -> #125
- [ ]  Linienstärken werden nicht mehr dargestellt (z. B. Transekte SoilSamplingCampaign, Zaun, etc) -> #126
- [ ]  former subplots: diese sind nur noch teil- transparent, damit wird die Darstellung der anderen Subplots überdeckt.
Former subplots sollten nur eine gestrichelte Außenlinie ohne Flächenfüllung haben.  -> #127
- [ ] SOIL-Subplot, Transekten entlang EP-Kante, Core 7 - Arthropods I überdecken in der Darstellung die anderen Subplots. Diese sind damit nur noch schwer lesbar. SOIL sollte in den Hintergrund, die anderen Subplots davor. -> #128
- [ ]  FOX-Gap: das Gap sollte ebenfalls ohne Flächenfarbe sein, damit die Suplots gesehen werden können -> #129
- [ ]  In den Tabellen sind nicht alle Subplots gelistet (z. B. logging trails auf A33-2, dort sind nur 2 der 7 logging trails in der Liste). (#49)
- [x] "Test" Subplot auf A33-2 ist nicht in der Tabelle gelistet, kann damit nicht editiert oder gelöscht werden (#49)
- [x]  Neue Linien-Subplots (neue logging trails) anlegen hat nicht funktioniert. -> jörg hat später geschrieben das es doch funktioniert
- [x] beim Bearbeiten von Plotcharts (manage Plot charts) werden die Spalten der Tabelle so schmal dargestellt, dass ich nur noch Teile der Spalten lesen kann (insbesondere Spalte "Name"). damit kann ich nicht mehr den gesuchten Subplot auswählen.
- [x] Wenn ich Subplots editieren will (Klick auf edit) passiert nichts. **(funktioniert, nachfragen!)**

**Comment by EleonoraPetzold** [comment]
all issues here now have their own issue.
